/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UrnaEletronica.View;

import UrnaEletronica.Model.CandidatoBergamota;
import UrnaEletronica.Model.CandidatoTangerina;
//port Imagens.*;


/**
 *
 * @author ARIEL
 */
public class TelaVotacao extends javax.swing.JFrame {

    /**
     * Creates new form TelaVotacao
     */
    public TelaVotacao() {
        initComponents();
    }
    
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFileChooser1 = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        txtBergamota = new javax.swing.JButton();
        txtTangerina = new javax.swing.JButton();
        nomeDaFruta = new javax.swing.JLabel();
        txtMexerica = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new javax.swing.OverlayLayout(jPanel1));

        txtBergamota.setText("BERGAMOTA");
        txtBergamota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBergamotaActionPerformed(evt);
            }
        });

        txtTangerina.setText("TANGERINA");
        txtTangerina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTangerinaActionPerformed(evt);
            }
        });

        nomeDaFruta.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        nomeDaFruta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nomeDaFruta.setText("Qual o nomenclatura você usa com mais frequência?");
        nomeDaFruta.setToolTipText("");

        txtMexerica.setText("MEXERICA");
        txtMexerica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMexericaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nomeDaFruta, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124))
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(txtTangerina, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtMexerica, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                        .addComponent(txtBergamota, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(122, Short.MAX_VALUE)
                .addComponent(nomeDaFruta, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTangerina, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMexerica, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBergamota, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTangerinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTangerinaActionPerformed
        // TODO add your handling code here:
        
       CandidatoTangerina candidato1 = new CandidatoTangerina("Tangerina");
      // candidato1.getNomeDoCandidato(txtTangerina.getText());
       candidato1.getHashNomeDoCandidato(txtTangerina.getText());
       candidato1.salvarVotosEmCandidatos();
       TelaConfirmacao confirmacao = new TelaConfirmacao();
       confirmacao.txtConfirmacao.setText(txtTangerina.getText());
       //confirmacao.jTextField1.setText(txtCPF.getText());
       setVisible(false);
       confirmacao.setVisible(true);
       
       
       
       
    }//GEN-LAST:event_txtTangerinaActionPerformed

    private void txtMexericaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMexericaActionPerformed
        // TODO add your handling code here:
        
       CandidatoTangerina candidato2 = new CandidatoTangerina("Mexerica");
          // candidato1.getNomeDoCandidato(txtTangerina.getText());
       candidato2.getHashNomeDoCandidato(txtMexerica.getText());
       candidato2.salvarVotosEmCandidatos();
       TelaConfirmacao confirmacao = new TelaConfirmacao();
       confirmacao.txtConfirmacao.setText(txtMexerica.getText());
       //confirmacao.jTextField1.setText(txtCPF.getText());
       setVisible(false);
       confirmacao.setVisible(true);
      
       
       
    }//GEN-LAST:event_txtMexericaActionPerformed

    private void txtBergamotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBergamotaActionPerformed
        // TODO add your handling code here:
         CandidatoBergamota candidato3 = new CandidatoBergamota("Bergamota");
       candidato3.getHashNomeCandidatoBergamota(txtBergamota.getText());
       candidato3.salvarVotosEmCandidatosBergamota();
       TelaConfirmacao confirmacao = new TelaConfirmacao();
       confirmacao.txtConfirmacao.setText(txtBergamota.getText());
       //confirmacao.jTextField1.setText(txtCPF.getText());
       setVisible(false);
       confirmacao.setVisible(true);
    }//GEN-LAST:event_txtBergamotaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVotacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVotacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVotacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVotacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaVotacao().setVisible(true);
            }
        });
    }
    
    public void receptor(String receptor) {
        txtTangerina.setText(receptor);
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nomeDaFruta;
    public javax.swing.JButton txtBergamota;
    public javax.swing.JButton txtMexerica;
    public javax.swing.JButton txtTangerina;
    // End of variables declaration//GEN-END:variables
}
