/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TelaDeLogin;

/**
 *
 * @author ARIEL
 */
public class TelaDeVotacao extends javax.swing.JFrame {

    /**
     * Creates new form TelaConfirmacao
     */
    public TelaDeVotacao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        VotarMexerica = new javax.swing.JToggleButton();
        VotarTangerina = new javax.swing.JToggleButton();
        VotarBergamota = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Qual o nome da fruta abaixo?");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(33, 76, 332, 30);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(44, 145, 82, 28);

        VotarMexerica.setText("2- MEXERICA");
        VotarMexerica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VotarMexericaActionPerformed(evt);
            }
        });
        getContentPane().add(VotarMexerica);
        VotarMexerica.setBounds(370, 220, 130, 50);

        VotarTangerina.setText("1 - TANGERINA");
        VotarTangerina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VotarTangerinaActionPerformed(evt);
            }
        });
        getContentPane().add(VotarTangerina);
        VotarTangerina.setBounds(370, 150, 130, 50);

        VotarBergamota.setText("3 - BERGAMOTA");
        VotarBergamota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VotarBergamotaActionPerformed(evt);
            }
        });
        getContentPane().add(VotarBergamota);
        VotarBergamota.setBounds(370, 290, 130, 50);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Tela de Votação");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(66, 20, 332, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/kisspng-juice-tangerine-mandarin-orange-grapefruit-clement-tangerine-5ac096e4d811c1.938257371522570980885.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jLabel4.setMaximumSize(new java.awt.Dimension(300, 300));
        jLabel4.setMinimumSize(new java.awt.Dimension(100, 100));
        jLabel4.setPreferredSize(new java.awt.Dimension(400, 400));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 130, 260, 230);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VotarMexericaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VotarMexericaActionPerformed
        // TODO add your handling code here:
        //CandidatoMexerica votarMexerica = new CandidatoMexerica();
    }//GEN-LAST:event_VotarMexericaActionPerformed

    private void VotarTangerinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VotarTangerinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VotarTangerinaActionPerformed

    private void VotarBergamotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VotarBergamotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VotarBergamotaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDeVotacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDeVotacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDeVotacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDeVotacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDeVotacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton VotarBergamota;
    private javax.swing.JToggleButton VotarMexerica;
    private javax.swing.JToggleButton VotarTangerina;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
